project_id = "iifkrhsuvxejgihubwku"

[auth]
site_url = "https://eva.useaima.com"
additional_redirect_urls = [
  "https://eva.useaima.com/auth",
  "http://localhost:5173/auth",
  "http://127.0.0.1:5173/auth",
  "http://localhost:8080/auth",
  "http://127.0.0.1:8080/auth",
  "https://your-financial-compass-79380-alvins-iswekah-mukabane-s-projects.vercel.app/",
  "https://your-financial-compass-79380-alvins-iswekah-mukabane-s-projects.vercel.app/**",
  "https://your-*-financial-compass-79380-alvins-iswekah-mukabane-s-projects.vercel.app",
  "https://your-*-financial-compass-79380-alvins-iswekah-mukabane-s-projects.vercel.app/**",
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600

[auth.email.smtp]
enabled = true
host = "smtp.resend.com"
port = 587
user = "resend"
pass = "env(RESEND_API_KEY)"
admin_email = "noreply@useaima.com"
sender_name = "Alvins @ eva"

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
